// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchoolManagementCoreApplication.Models
{
    public partial class AllocationResult
    {
        [StringLength(18)]
        public string Message { get; set; }
    }
}
