// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SchoolManagementCoreApplication.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SchoolManagementCoreApplication.Models
{
    public partial interface ISchoolDatabaseContextProcedures
    {
        Task<List<AllocationResult>> AllocationAsync(int? studentId, int? degreeId, int? teacherId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeleteStudentResult>> DeleteStudentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentResult>> GetStudentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsResult>> GetStudentsAsync(bool? active, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpsertStudentResult>> UpsertStudentAsync(int? id, string firstName, string lastName, string middleName, string preferredName, int? genderId, DateOnly? dateOfBirth, int? ethnicityId, string email, string phone, string address, bool? active, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
