// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using SchoolManagementCoreApplication.Models;

namespace SchoolManagementCoreApplication.Models
{
    public partial class SchoolDatabaseContext
    {

        [DbFunction("EmailExists", "dbo")]
        public static bool? EmailExists(string Email)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetDegreeNamesByStudent", "dbo")]
        public static string GetDegreeNamesByStudent(int? StudentId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetTeacherNamesByStudent", "dbo")]
        public static string GetTeacherNamesByStudent(int? StudentId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidBirthDate", "dbo")]
        public static bool? IsValidBirthDate(DateOnly? DateOfBirth)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidDegreeId", "dbo")]
        public static bool? IsValidDegreeId(int? DegreeId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidEmail", "dbo")]
        public static bool? IsValidEmail(string Email)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidEthnicityId", "dbo")]
        public static bool? IsValidEthnicityId(int? EthnicityId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidGenderId", "dbo")]
        public static bool? IsValidGenderId(int? GenderId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidPhone", "dbo")]
        public static bool? IsValidPhone(string Phone)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidStudentId", "dbo")]
        public static bool? IsValidStudentId(int? StudentId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsValidTeacherId", "dbo")]
        public static bool? IsValidTeacherId(int? TeacherId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("PhoneExists", "dbo")]
        public static bool? PhoneExists(string Phone)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("StudentNameExists", "dbo")]
        public static bool? StudentNameExists(string FirstName, string LastName)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
