// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementCoreApplication.Models;

public partial class StudentDegree
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int DegreeId { get; set; }

    public virtual Degree Degree { get; set; }

    public virtual Student Student { get; set; }
}