// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementCoreApplication.Models;

public partial class StudentTeacher
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int TeacherId { get; set; }

    public virtual Student Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}