// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementCoreApplication.Models;

public partial class Teacher
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public string PreferredName { get; set; }

    public int DegreeId { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public int GenderId { get; set; }

    public int EthnicityId { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public bool Active { get; set; }

    public virtual Degree Degree { get; set; }

    public virtual Ethnicity Ethnicity { get; set; }

    public virtual Gender Gender { get; set; }

    public virtual ICollection<StudentTeacher> StudentTeachers { get; set; } = new List<StudentTeacher>();
}